language: c

env: HOW_DOC=docs HOW_CONFIG=how.json HOW_OUT=_doc

before_install:
    - "if [ $TRAVIS_EVENT_TYPE == cron ]; then rm -rf ~/.opam; fi"

install:
    - wget https://ocsigen.org/how.sh
    - . how.sh
    - how-install

script:
    - how-generate
    - how-redirect "$HOW_LATEST/manual/manual" $HOW_OUT/index.html
    - how-redirect-manual 2.4.3 1.0.0
    - how-redirect-manual 2.4.3 1.1.0
    - how-redirect-manual 2.4.3 2.0.0
    - how-redirect-manual 2.4.3 2.1.0
    - how-redirect-manual 2.4.3 2.1.1
    - how-redirect-manual 2.4.3 2.2.0
    - how-redirect-manual 2.4.3 2.2.1
    - how-redirect-manual 2.4.3 2.3.0
    - how-redirect-manual 2.4.3 2.3.1
    - how-redirect-manual 2.4.3 2.3.2
    - how-redirect-manual 2.4.3 2.4.0
    - how-redirect-manual 2.4.3 2.4.1
    - how-redirect-manual 2.4.3 2.4.2
    - how-redirect-manual $HOW_LATEST latest

before_cache:
    - opam clean
    - rm -rf $HOME/.opam/ocaml-base-compiler.4.06.1/.opam-switch/sources/html_of_wiki

cache:
  directories:
    - $HOME/.opam

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GHP_TOKEN
  local-dir: _doc
  on:
    branch: wikidoc
