version: "{build}"

shallow_clone: true

environment:
  global:
    CYGWIN: C:\Cygwin
    CYGSH: C:\Cygwin\bin\bash -lc
  matrix:
    - {SYSTEM: cygwin, COMPILER: 4.01}
    - {SYSTEM: cygwin, COMPILER: 4.02}

install:
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/$env:SYSTEM/x86/ocaml/$env:COMPILER/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/$env:SYSTEM/x86/camlp4/$env:COMPILER/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/$env:SYSTEM/x86/opam/1.2/install.ps1") | PowerShell -Command -'
  - utils\appveyor-%SYSTEM%-install.bat

build_script:
  - utils\appveyor-%SYSTEM%-build.bat
